print ("Hello World")
print ("Welcome to DevOps World training")
print ("Hope you will carry this thing")
print ("you need to settle")
print ("we I am think that I am working right!")
print("Nor sure but thing that this rebase will work")